language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- node

os:
- linux
- osx

git:
  depth: 1

env:
  global:
    secure: dHZkfjL0eagnG2UBm4cR3DVFgwyPAc4gr48sBfIPrdee6Zm3uz9ctQcSjTmKtOKKQd0g4BNMTgvpi44JuZX79N67fygWmWMCSKSPInkSsnPJLOVArhC0F+T8Eei19hwaARwFZ++MCmsIUoyFtjLsCaG4tO+6jM1uu/0FXDwL//XcYZefMRLMzGv1j3RLJk9dQfY6InilCEqjvcbMlktNbECJs04GVWSl3RsYTffHYUft+0qrwKKA+eDKLCf3qC5hJ6TLW0foF+fNu16jh/gZtw94b8dhpdEqd9gO0bXz4/jt+sI+ubczio0IX1EdG2WLFJxPQvVNz38Bqof1fBe3hesL64rsr3PFuCPs8kdMIHHkKoDLfRS/K/3+PW25XteHkFOEi8UJg6BB5sw1zDhqKc42gybMDphYOIkUkdoNMbUmFJKJy01pP7jqP45ye0sXL0Gff3YPZGfVry7gK+Bh63esQEaCnPrScrdpB8ycKW+KS+ddv6KWUNdQKSHsEWtikQ505WYHtqZ81XIMP6HXLV3H/lMRfT43NOALUBpauuJ+JXM5f1yl8rSJHY0YoA2CUScmUrgJLQ5KsBdRPq5GXS7TKTuRZ7O7J/yWoAys2ok8BOAiq5sths+oZ7LMAgHkTLeik67arWTVvy+wiDcXpMpcak3W8pm8cdNDbVu96WM=

jobs:
  include:
  - stage: deploy
    if: type = pull_request
    os: linux
    node_js: node
    script:
    - |
      if [[ -n $(git diff --name-only package-lock.json) ]]
      then
        git config credential.helper "store --file=.git/credentials" || exit $?
        echo "https://${GH_TOKEN}:@github.com" 2> /dev/null > .git/credentials || exit $?
        git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git || exit $?
        git add package-lock.json || exit $?
        git commit -m "update package-lock.json" || exit $?
        git push origin HEAD:$TRAVIS_PULL_REQUEST_BRANCH &> /dev/null || exit $?
      fi

before_install:
  # package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'

before_script:
- git config --global user.name "Travis Bot"
- git config --global user.email "\<\>"

script:
- npm run example
- npm test
